### ISSUE TITLE
Needs to change current server to render server 

### ISSUE THREAD

**Issue by usha-madithati** [usha-madithati/esmart.github.io#320] opened 2024-06-23 03:14 UTC

**Comment by Ansh101112** [comment] 2024-06-23 05:38
Done 👍

**Comment by techy4shri** [comment] 2024-06-23 18:15
There is no description, nothing and this issue is assigned? How?

**Comment by Ansh101112** [comment] 2024-06-23 19:13
> There is no description, no format, nothing and this issue is assigned? How?

Actually the PR is raised before the issue that's why the PA has assigned without description see the pr that merged.

**Comment by techy4shri** [comment] 2024-06-23 19:27
That's not how it works. That's collaboration on personal level. This repository is under GSSoC 2024. And you need to raise an issue first. This is simply breach of code of conduct.

**Comment by usha-madithati** [comment] 2024-06-24 01:10
> There is no description, no format, nothing and this issue is assigned? How?

Heyyy hiii I don't know who are you whether a contributor or I don't know . Iam the PA of this repo. See here we are contacting him through discord server and we have been telling him about our issue there and he has been developing according to our issue in order to resolve that . Whatever you have asked is correct we have been creating the issue 1st you can check after creation of issue only we have been merging the pr . And 1 more thing we are frequently contacting him because he is contributing well to our project we have contacted other contributors too but they haven't done anything so why will we even go and look for some one else when he is doing good . So please do know that and we have talked this to project manager also.
Thank you .

**Comment by usha-madithati** [comment] 2024-06-24 01:12
> There is no description, no format, nothing and this issue is assigned? How?

And one more why do even need description for that the issue itself clearly explains what to do and even if you don't understand you would have dropped a message there we would have contacted you if you were that much of intrested

**Comment by MinavKaria** [comment] 2024-06-24 09:34
And out of @Ansh101112 's 49 PR , 42 are from this repo that to continuos. Where others are rarely allowed to contribute. I feel this is politics that is going on here.I am ok contributing as much as he wants , but also allow others too as much as @Ansh101112 sh is doing , that my point.

**Comment by usha-madithati** [comment] 2024-06-24 10:19
> And out of @Ansh101112 's 49 PR , 42 are from this repo that to continuos. Where others are rarely allowed to contribute. I feel this is politics that is going on here.I am ok contributing as much as he wants , but also allow others too as much as @Ansh101112 sh is doing , that my point. 

Heyy hii @MinavKaria I have clearely explained above you can check which is in the same chat . It's not like we were not checking other issues created by contributors. Who told you that we were not checking the issues in the same repo you can go and check that arround 10 to 12 issues I have asked for the contributors details to contact them and explain them the issue . People will tell that they were ok And they can work on that issue and after 4 or 5 days they will come and say that mam sorry I can't work on this .this is the situation that we have face like mostly I have seen 4 or 5 contributors like this . And one more thing you told that we are letting @Ansh101112 to win. We are sorry for that you can go and check our repo prs and you can see we gave him all the valid levels for whatever the work ha had done . You can't say that we are letting him to win because we are fair enough and giving levels to the work he has done .and 1 more thing you told that you will complaint this to admin right I have clearly told admin regarding this . 
And even you are not believing right that we have contacted other contributors you can check the chatbox under some issues. I will even send you some screenshots so that you guys can belive that we have contacted many other contributors and they weren't working well. We don't even know @Ansh101112 if you are that much interested to work ping us we will work together. So please don't talk that you know everything.
Thank you. Even now if you wants to talk again feel free to contact us.

**Comment by MinavKaria** [comment] 2024-06-24 10:54
@usha-madithati Sorry for my misunderstanding, and thank you for the clarification. Please checkout others issues and assign them. I have also sent some issues please check that out and let me know #319 . Please give chances to others too and please try to contact via issue and then PR, instead of blank issue, this will make others also misunderstand like me.

**Comment by usha-madithati** [comment] 2024-06-24 10:56
> @usha-madithati Sorry for my misunderstanding, and thank you for the clarification. Please checkout others issues and assign them. I have also sent some issues please check that out and let me know #319 . Please give chances to others too and please try to contact via issue and then PR, instead of blank issue, this will make others also misunderstand like me. 

Ok no problem it's not like we aren't giving chance to others we are fine if more and more are contributing to our project. I will check your issues . You guys better comment on the issues created by us so that it will be helpful for us also . I will check your issue.

**Comment by MinavKaria** [comment] 2024-06-25 04:28
Please share me the discord server link where I could also get to know the issues and help you improve the website

**Comment by usha-madithati** [comment] 2024-06-25 06:47
Ok

**Closed** 2024-06-26 07:35 UTC
Labels: gssoc

**Comment by techy4shri** [comment] 2024-06-26 19:29
> > There is no description, no format, nothing and this issue is assigned? How?
> 
> And one more why do even need description for that the issue itself clearly explains what to do and even if you don't understand you would have dropped a message there we would have contacted you if you were that much of intrested

Description is needed to describe the issue-elaborate on it, explain the proposed solution and such. Because there is supposed to be a format. And the issue is supposed to be raised before the PR, as explained by the core members of GSSOC.
